/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_contact_LoadJni */

#ifndef _Included_com_example_contact_LoadJni
#define _Included_com_example_contact_LoadJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_contact_LoadJni
 * Method:    getResult
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_contact_LoadJni_getResult
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
